# 基本网站信息
baseURL = "https://cardwas.com/"
languageCode = "en-us"
title = "CardWas"
defaultContentLanguage = "en"

# 如果你不使用 Hugo 主题，可以删除 theme
# theme = "introduction"

# 渲染原始 HTML，如果你的 Markdown 里会插入 HTML
[markup.goldmark.renderer]
unsafe = true

# 可选自定义参数（模板用）
[params]
whatsapp = "8619007244694,8615827853613"
email = "jianglinwang727@gmail.com"
phone = "+8617764108746"
address = "Lagos, Nigeria"

# 构建配置（可选）
[build]
writeStats = true
